version: "3.8"

services:
  nexus:
    image: "${IMAGE}"
    ports:
      - "${EXPOSED_PORT}:8081"
    volumes:
      - nexus:/nexus-data
    deploy:
      placement:
        constraints:
          - "node.labels.nexus == 1"

volumes:
  nexus:
